const fs = require('fs');

const cs06_07 = [
{
    "id": "cs06",
    "title": "Case Study: YouTube / Netflix Video Streaming",
    "parent_id": null,
    "order": 23,
    "tags": ["case-study", "video", "cdn", "transcoding", "blob"],
    "summary": "Design a global video streaming platform like YouTube or Netflix capable of ingesting massive video uploads, transcoding them instantly, and streaming 4K video to millions of concurrent users without buffering.",
    "explanation": {
        "overview": "A video streaming platform is a fundamentally different system design challenge compared to standard web apps. It requires handling massive, unpredictable payloads (Uploads), intensive CPU-bound processing (Transcoding), and globally distributed static asset delivery (CDN). The architecture splits into a Control Plane (handling user metadata, search, comments) and a Data Plane (handling the actual bytes of the video files).",
        "how_it_works_internally": "INTERNAL Mechanics: When a user uploads a video, they do not send 5GB through your API Gateway. Instead, the server generates a Pre-Signed URL allowing the client to upload chunks directly to a Blob Storage bucket (AWS S3) using multi-part upload. Once the upload finishes, an Event Notification triggers a Kafka queue. A fleet of Worker Nodes consumes this queue to perform Video Transcoding, converting the raw file into Dash/HLS streams at various resolutions (1080p, 720p, 480p). Finally, these processed chunks are replicated to global CDNs. When a viewer clicks play, their client downloads an index file (Manifest) and begins pulling chunks directly from the nearest CDN edge node.",
        "step_by_step": [
            {
                "step": 1,
                "title": "Multi-part Direct Upload",
                "detail": "Client requests an upload token. Server returns a signed S3 URL. Client uploads a 2GB file in 5MB chunks directly to storage, entirely bypassing the web servers."
            },
            {
                "step": 2,
                "title": "Asynchronous Transcoding Pipeline",
                "detail": "S3 triggers an event to Kafka. Transcoder workers pull the video, split it by timeframes (e.g., 10-second segments), and process them in parallel across hundreds of cores."
            },
            {
                "step": 3,
                "title": "Adaptive Bitrate Streaming (ABR)",
                "detail": "The transcoder outputs a manifest file (M3U8). The client downloads this file and continuously monitors its own network speed. If the network drops, the client seamlessly requests lower resolution chunks from the CDN."
            },
            {
                "step": 4,
                "title": "Metadata Database Scaling",
                "detail": "While video files live in S3/CDN, metadata (Title, Description, Likes) lives in a Sharded RDBMS (e.g., Vitess/MySQL) to support complex ACID transactions and search indexing."
            }
        ],
        "key_concepts": [
            {
                "term": "Pre-Signed URLs",
                "definition": "INTERNAL: A cryptographic signature generated by the backend granting a client temporary, restricted access to upload directly to a third-party storage provider (S3). Prevents the backend from becoming an I/O bottleneck."
            },
            {
                "term": "Content Delivery Network (CDN)",
                "definition": "A globally distributed network of proxy servers deployed in multiple data centers. Their goal is to serve content to end-users with high availability and high performance by caching video chunks physically near the user's ISP."
            }
        ],
        "examples": [
            {
                "title": "Python Implementation Snippet: Transcoding Worker",
                "description": "Concrete Python code proving how to trigger asynchronous FFmpeg video compression on a worker node.",
                "code": "import subprocess\nimport boto3\n\ndef transcode_segment(s3_input_key, s3_output_bucket, resolution):\n    # Download chunk from S3\n    download_from_s3(s3_input_key, 'input.mp4')\n    \n    # Execute FFmpeg via subprocess to enforce strict CPU limits\n    cmd = ['ffmpeg', '-i', 'input.mp4', '-vf', f'scale=-1:{resolution}', '-crf', '23', 'output.mp4']\n    subprocess.run(cmd, check=True)\n    \n    # Upload transcoded chunk to edge origin\n    output_key = s3_input_key.replace('.mp4', f'_{resolution}p.mp4')\n    boto3.client('s3').upload_file('output.mp4', s3_output_bucket, output_key)\n    return output_key"
            },
            {
                "title": "Java Implementation Snippet & Concurrency",
                "description": "Production Java snippet demonstrating generation of pre-signed URLs securely.",
                "code": "public class UploadService {\n    private final AmazonS3 s3Client;\n    \n    public URL generatePresignedUrl(String bucketName, String objectKey) {\n        // Enforce temporary access strictly limited to 15 minutes\n        Date expiration = new Date();\n        long expTimeMillis = expiration.getTime() + (1000 * 60 * 15);\n        expiration.setTime(expTimeMillis);\n        \n        GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(bucketName, objectKey)\n                .withMethod(HttpMethod.PUT)\n                .withExpiration(expiration);\n        return s3Client.generatePresignedUrl(request);\n    }\n}"
            },
            {
                "title": "Decision Matrix & Tradeoffs: Streaming Protocols",
                "description": "Evaluating how to deliver video over the internet.",
                "code": "OPTION RTMP vs OPTION HLS/DASH\n------------------------------\nPros RTMP: Extremely low latency (1-3 seconds), good for live streaming (Twitch).\nCons RTMP: Requires a persistent connection, easily blocked by firewalls, does not work efficiently over standard CDNs.\nPros HLS: Runs over standard HTTP port 80/443, naturally cached by all CDNs, supports adaptive bitrate.\nCons HLS: High latency (10-30 seconds). (YouTube relies primarily on MPEG-DASH)."
            },
            {
                "title": "Failure Modes & Exception Handling",
                "description": "CDN cache misses and Transcoding faults.",
                "code": "try-catch fallback mechanics:\n1. TranscoderOOMException: Video transcoding memory usage is unpredictable. If the worker crashes, the Kafka queue message remains unacknowledged. Another worker picks it up after the visibility timeout. If it fails 3 times, it shifts to a Dead Letter Queue (DLQ) for manual inspection.\n2. CDN Origin Shield Drop: Instead of 10,000 Edge nodes slamming the S3 Origin upon a cache miss (Thundering Herd), they query an 'Origin Shield' regional cache. If the Shield fails, request coalescence groups identical chunk requests into a single origin pull."
            }
        ]
    },
    "configurable_params": [
        {
            "name": "Library Configuration Parameters (Kafka Consumer)",
            "default": "auto.offset.reset = 'latest'",
            "effect": "Modify parameter `max.poll.interval.ms = 3600000` (1 hour) for transcoding workers.",
            "tradeoff": "Transcoding a 4K video takes massive time. If the poll interval is too short, Kafka assumes the worker died, reassigns the partition, and causes infinite duplicate processing pipelines."
        }
    ],
    "advanced_tweaks": [
        {
            "technique": "State Management Techniques",
            "when_to_use": "Handling client view-counters and resume-playback state.",
            "how": "View counts cannot be synchronously updated in an RDBMS per view. The stateless Web Servers drop view events onto a Kafka topic. A streaming Analytics engine (Flink) aggregates views in memory every 5 seconds and flushes the bulk state `UPDATE video SET views = views + 400` to the database."
        }
    ],
    "diagram": {
        "type": "mermaid",
        "title": "YouTube Upload & Streaming Architecture",
        "description": "Control Plane vs Data Plane Architecture.",
        "data": {
            "mermaid_source": "graph TD\n  Client[Device] --> |1. Get Pre-Signed URL| API[API Gateway]\n  API --> MetaDB[(Metadata RDBMS)]\n  Client --> |2. Multi-part Upload| S3[(Amazon S3 Raw Storage)]\n  S3 --> |3. Event Trigger| Kafka[Kafka Encoding Queue]\n  Kafka --> Encoder[Transcoding Workers]\n  Encoder --> |4. Store Processed| S3Trans[(Processed Video S3)]\n  S3Trans --> CDN[Global CDN / Edge Nodes]\n  Client --> |5. Stream Video| CDN\n  style S3 fill:#ff9900\n  style CDN fill:#4d4dff"
        }
    },
    "limitations": [
        "Storage Costs: Storing 4K video in 5 different formats is astronomically expensive. TWEAK: Only transcode popular videos into 4K immediately. For long-tail (rarely viewed) videos, only store 720p. If a video goes viral, trigger an asynchronous upscale/transcode to 4K dynamically.",
        "Global Replication Delay: A video uploaded in Tokyo might take minutes to replicate to a CDN in New York. TWEAK: Serve the video directly from the core S3 bucket while replication is in-flight, accepting temporary higher latency for instant availability."
    ],
    "technologies_used": [
        {
            "technology": "Vitess (YouTube DB Sharding)",
            "details": "YouTube created Vitess (a database clustering system for horizontal scaling of MySQL) to handle massive metadata scaling. It abstracts the routing logic so the application code interacts with what looks like a single massive database, while Vitess handles sharding underneath."
        },
        {
            "technology": "FFmpeg",
            "details": "The industry standard open-source library for manipulating, converting, and streaming audio and video. Used universally by FAANG for the core transcoding pipeline."
        }
    ]
},
{
    "id": "cs07",
    "title": "Case Study: Uber / Lyft Ride Dispatch System",
    "parent_id": null,
    "order": 24,
    "tags": ["case-study", "dispatch", "geospatial", "streaming", "microservices"],
    "summary": "Design a highly available geographical dispatch system (DISCO) orchestrating millions of active drivers and riders with sub-second matching, relying on S2 Geometry and Gossip Protocols.",
    "explanation": {
        "overview": "A ride-sharing application is a massive real-time marketplace. It tracks the hyper-local location of millions of moving drivers every 4 seconds, maintaining this massive state entirely in memory for instant queries. The core challenge is highly contentious geospatial searching: finding the closest driver to a rider based on road networks, ETA, and direction, while handling constant network drops.",
        "how_it_works_internally": "INTERNAL Mechanics: Uber's Dispatch Optimization system (DISCO) divides the earth into hexagonal buckets using the H3 (or S2) geometry library. When a driver sends a GPS ping, API gateways route it to a stateful Dispatch Server handling their specific geographic bucket. The server holds the cars in memory. When a rider requests a trip, the system determines their H3 bucket, queries the cars in that bucket (and adjacent ones), and calculates ETA using a routing engine. To ensure high availability and prevent single points of failure, the servers managing these geospatial buckets utilize node ring-hashing (Ringpop), communicating via the SWIM Gossip protocol to detect failures.",
        "step_by_step": [
            {
                "step": 1,
                "title": "Driver State Ingestion",
                "detail": "Drivers push GPS points every 4 seconds. The API gateway drops this directly into Kafka. A streaming analytics pipeline (Flink/Spark) immediately updates the in-memory Dispatch grid."
            },
            {
                "step": 2,
                "title": "Geospatial Indexing",
                "detail": "GPS (Lat/Long) cannot be queried quickly. The system converts Lat/Long into a highly optimized 64-bit integer string representing an H3 hex cell."
            },
            {
                "step": 3,
                "title": "Rider Matching",
                "detail": "Rider opens app. System queries the H3 cell. It finds 15 drivers. It sends these drivers to the ETA routing engine (which considers traffic, one-way streets). An ML model scores the drivers, picks the ultimate best match, and triggers the trip offer."
            },
            {
                "step": 4,
                "title": "Trip State Management",
                "detail": "Once a trip begins, the state (driver, rider, route) transitions from the volatile memory grid into a strongly consistent clustered database (Cassandra) for billing and auditing."
            }
        ],
        "key_concepts": [
            {
                "term": "H3 / S2 Geospatial Indexing",
                "definition": "INTERNAL: A mathematical library (H3 by Uber, S2 by Google) that converts Earth's sphere into 3D geometry cells. It reduces the complex floating-point math of proximity searches (Haversine formula) into a simple, lightning-fast O(1) dictionary key lookup."
            },
            {
                "term": "Gossip Protocol (SWIM)",
                "definition": "In a cluster of 1,000 servers mapping the city grid, a centralized master node tracking server health becomes a bottleneck. In a Gossip protocol, machines randomly ping a few peers every second. Faults propagate organically like a virus, allowing the cluster to self-heal."
            }
        ],
        "examples": [
            {
                "title": "Python Implementation Snippet: Geospatial State Tracking",
                "description": "Concrete Python code demonstrating how driver locations are mapped to H3 indices in memory.",
                "code": "import h3\n\n# In-memory grid mapping H3 cell ID to a set of active drivers\ncity_grid = {}\n\ndef update_driver_location(driver_id, lat, lng):\n    # Resolution 9 is ~0.1 sq kilometers (perfect for city blocks)\n    cell_id = h3.geo_to_h3(lat, lng, resolution=9)\n    \n    # In a real system, we'd remove them from their old cell too\n    if cell_id not in city_grid:\n        city_grid[cell_id] = set()\n        \n    city_grid[cell_id].add(driver_id)\n    \ndef find_nearby_drivers(rider_lat, rider_lng):\n    center_cell = h3.geo_to_h3(rider_lat, rider_lng, resolution=9)\n    # Get the center cell and its immediate neighbors (1 ring out)\n    neighborhood = h3.k_ring(center_cell, 1)\n    \n    available_drivers = []\n    for cell in neighborhood:\n        if cell in city_grid:\n            available_drivers.extend(list(city_grid[cell]))\n    return available_drivers"
            },
            {
                "title": "Java Implementation Snippet & Concurrency",
                "description": "Production Java snippet demonstrating concurrent in-memory updates for blazing fast dispatcher writes.",
                "code": "public class DispatchGrid {\n    // ConcurrentHashMap allows lock-free reads while drivers constantly update GPS\n    private final Map<String, ConcurrentLinkedQueue<Driver>> h3Grid = new ConcurrentHashMap<>();\n    \n    public void processDriverPing(Driver driver) {\n        h3Grid.computeIfAbsent(driver.getH3Index(), k -> new ConcurrentLinkedQueue<>())\n              .add(driver);\n              \n        // Asynchronously flush historical data to Cassandra to avoid blocking the main thread\n        CompletableFuture.runAsync(() -> cassandraRepo.saveHistorical(driver));\n    }\n}"
            },
            {
                "title": "Decision Matrix & Tradeoffs: Location Storage",
                "description": "Evaluating where to store live coordinates.",
                "code": "OPTION RDBMS (PostGIS) vs OPTION In-Memory Grid (Redis/Ringpop)\n---------------------------------------------------------------\nPros PostGIS: Standard SQL querying, built-in spatial indexes, ACID.\nCons PostGIS: Abysmally slow for 1 million writes per second. B-Tree fragmentation destroys disks.\nPros In-Memory: Sub-millisecond read/writes, effortlessly handles massive ingestion.\nCons In-Memory: Volatile. Crashes lose driver locations (forcing rely on constant live client pings)."
            },
            {
                "title": "Failure Modes & Exception Handling",
                "description": "Datacenter crashes and corrupted states.",
                "code": "try-catch fallback mechanics:\n1. ServerCrashException: If a Node tracking 'Manhattan' dies, the Gossip protocol detects the failure. Consistent Hashing redistributes the Manhattan H3 keys to neighbor nodes. Driver apps pinging every 4 seconds instantly repopulate the new nodes.\n2. Total Datacenter Failure: Uber uses 'Driver Phones as Backup'. The server periodically pushes an encrypted digest of the trip state to the driver's phone. If the datacenter dies completely, a backup datacenter boots up and reconstructs the active trip directly from the driver's phone payload."
            }
        ]
    },
    "configurable_params": [
        {
            "name": "Library Configuration Parameters (H3 Resolution)",
            "default": "Resolution 9 (approx 0.1 sq km).",
            "effect": "Modify parameter to Resolution 10 (tighter grid) or Resolution 8 (larger grid).",
            "tradeoff": "A tighter grid means finding drivers closer to the exact street, but requires calculating routes for far more adjacent rings (k-ring searches) if the center cell is empty. It massively increases CPU load on the mapping algorithm."
        }
    ],
    "advanced_tweaks": [
        {
            "technique": "State Management Techniques",
            "when_to_use": "Handling millions of active geospatial actors.",
            "how": "Use Stateful Microservices via Ringpop/Consistent Hashing. Avoid saving transient GPS points to a database entirely. Instead, use a hashing ring to ensure Driver A's pings always route to Node X. Node X keeps Driver A in a local dictionary variable. It's wildly fast and inherently horizontally scalable."
        }
    ],
    "diagram": {
        "type": "mermaid",
        "title": "Uber Dispatch (DISCO) Architecture",
        "description": "Stateful Geo-Indexing and Real-Time Kafka pipelines.",
        "data": {
            "mermaid_source": "graph TD\n  Driver[Driver GPS] -->|Ping 4s| API[API Gateway]\n  API --> Kafka[Kafka Stream / Flink]\n  Kafka --> GeoCluster[Geospatial Stateful Cluster]\n  \n  Rider[Rider App] --> |Request Ride| Matcher[Matching Engine]\n  Matcher --> GeoCluster\n  Matcher --> Routing[ETA & Map Routing Engine]\n  Matcher -.-> |Pick Best| TripDB[(Trip Cassandra DB)]\n  \n  subgraph \"Ringpop Gossip Cluster\"\n    GeoCluster\n  end"
        }
    },
    "limitations": [
        "Network Partitions: If the network splits, two data centers might both try to manage the same trip, causing double billing. TWEAK: Rely on strict Quorum writes in the Trip Database (Cassandra) to ensure only the partition with the majority votes can update the billing state.",
        "High CPU on Matching: Calculating 50 permutations of ETAs through heavy traffic grids for every rider is expensive. TWEAK: Pre-calculate routing constraints in the background aggressively. Pre-build the graph data structure instead of doing A* pathfinding live."
    ],
    "technologies_used": [
        {
            "technology": "Ringpop (Uber OSS)",
            "details": "A Node.js library that brings application-layer sharding to your network. It allows applications to distribute data across multiple nodes and automatically handles failures using the SWIM gossip protocol without needing external systems like ZooKeeper."
        },
        {
            "technology": "Apache Kafka",
            "details": "The absolute backbone of the system. Serves as a terrifyingly massive shock absorber. If the internal systems go down, drivers keep pinging, and Kafka simply spools the data to disk until the dispatch servers recover."
        }
    ]
}
];

cs06_07.forEach(cs => {
    fs.writeFileSync('/Users/211446/Grokking-System-Design/course-content/chapters/' + cs.id + '_' + cs.title.toLowerCase().replace(/[^a-z0-9]+/g, '_').substring(0, 15) + '.json', JSON.stringify(cs, null, 4));
});
console.log('Successfully generated cs06 and cs07 json files.');
